sudo: false
language: node_js
node_js:
- '4'
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: sysadmin@grabone.co.nz
  api_key:
    secure: I/yER95QhcQTGTcp+do0OYWZYJYSuHQ28wokxp+JkRPTpRkdShEKKXzLNgYk14s7jZyF85Gd9HZsGfZDr9Kd3K821uKysi8/BtYwRBGUtq+IjAn32wo7xuCRw9hWhh09rrKs/YFHTAbzGkTV0B+c2tbm/6o1HZypisqdzFBrLqyJCc6BuEB7p5lHvwGkVNHFV+VX005DUKPCcsyPjkpiwo9AXDhf40UKgRam0XP62rlGqTOXLdC/UdRZj70vtuiHm1V2dyMi3TEQp4kBenlwtpDYs+wZd75UN8y8LLS/oOD/O7LL8qFeSjnukO+b+OpyS+yO+Kkqfae+UqK+GIVZZ/5/mjyezxeyEUjKo8RU0TkwCoGZjbhgOJdcO+GJ3fBkFym/7NZYp/Fy78+leBrwrlnWa1swbD+C4rP5T6+Z6nYh5rtFUSDj8mruOeIqqnvbZsyJE0Ho418Y6elp2b+FfO3Kl7zPkUZBhP8s+zwwlubAwTk+WWlWGoAKLoKngM8L1I/D0D9oEFIvpF57QhI+DXFjsB/EjOmyuL8e0np1rnHmD23po7f0KlM6ugcGzLXc/XnuzbZ3bOgermW2dKLG3RbuBZZUTUVnLk2Xpv9A6OwFrLT7uxzQPHgJpzUWxZyOz4sI04v6l2xTXYLrLhk8BFMTLzCy2KkM/lpPvXAfJM0=
  on:
    tags: true
    repo: NZME/pagination-class
